name: Publish and Deploy

on:
  push:
    branches:
      - main

jobs:
  Publish:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          clean: false   # ðŸ”¹ uploads papkasini tozalamasin

      - name: Build Docker image
        run: sudo docker compose build

      - name: Push Docker image
        run: |
          echo $DOCKER_PASSWORD | sudo docker login -u $DOCKER_USERNAME --password-stdin
          sudo docker compose push

  Deploy:
    name: Deploy
    needs: Publish
    runs-on: eskiz_srv
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Deploy
        run: |
          # ðŸ”¹ .env fayl yaratish
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" > .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env

          # ðŸ”¹ Docker login
          echo $DOCKER_PASSWORD | sudo docker login -u $DOCKER_USERNAME --password-stdin

          # ðŸ”¹ Docker pull va run
          sudo docker compose pull
          sudo docker compose up -d --remove-orphans
